/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PresentationLayer;

import TransferObject.Research;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ch-sa
 */
public class Nav extends javax.swing.JPanel {

    /**
     * Creates new form Drawer
     */
    public Nav() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        researchLbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        researchLbl1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(47, 18, 76));

        researchLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        researchLbl.setForeground(new java.awt.Color(254, 194, 96));
        researchLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        researchLbl.setText("Research");

        researchLbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        researchLbl1.setForeground(new java.awt.Color(254, 194, 96));
        researchLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        researchLbl1.setText("Smart Search");
        researchLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                researchLbl1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(researchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(researchLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(researchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(researchLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void researchLbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_researchLbl1MouseClicked
       
        LandingPage landingPage = (LandingPage) this.getTopLevelAncestor();
        CardLayout cardLayout = (CardLayout) landingPage.mainPanel.getLayout();
        cardLayout.show(landingPage.mainPanel, "card4");
       //// Research research = fascadeBLL.getResearch(openResearchNameTextField.getText());
        //landingPage.researchPanel1.setReseach(research);

    }//GEN-LAST:event_researchLbl1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel researchLbl;
    private javax.swing.JLabel researchLbl1;
    // End of variables declaration//GEN-END:variables
}
