/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PresentationLayer;

import BusinessLogicLayer.*;
import TransferObject.Research;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ch-sa
 */
public class ResearchListPanel extends javax.swing.JPanel {

    IFascadeBLL fascadeBLL;

    /**
     * Creates new form ResearchListPanel
     */
    public ResearchListPanel() {
        initComponents();
        fascadeBLL = new FascadeBLL();
        populateResearchTable(fascadeBLL.getAllResearches());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        researchTable = new javax.swing.JTable();
        createResearchBtn = new javax.swing.JButton();
        updateResearchBtn = new javax.swing.JButton();
        deleteResearchBtn = new javax.swing.JButton();
        mergeResearchBtn = new javax.swing.JButton();
        actionPanel = new javax.swing.JPanel();
        blankPanel = new javax.swing.JPanel();
        deletePanel = new PresentationLayer.PanelRound();
        deleteBtn = new javax.swing.JButton();
        deleteBackBtn = new javax.swing.JButton();
        createResearchLbl7 = new javax.swing.JLabel();
        createResearchLbl8 = new javax.swing.JLabel();
        deleteResearchNameTextField = new javax.swing.JTextField();
        updatePanel = new PresentationLayer.PanelRound();
        updateBtn = new javax.swing.JButton();
        updateBackBtn = new javax.swing.JButton();
        newNameTextField = new javax.swing.JTextField();
        createResearchLbl4 = new javax.swing.JLabel();
        createResearchLbl5 = new javax.swing.JLabel();
        researchUpdateNameTextField = new javax.swing.JTextField();
        createResearchLbl6 = new javax.swing.JLabel();
        createPanel = new PresentationLayer.PanelRound();
        createAddBtn = new javax.swing.JButton();
        createBackBtn = new javax.swing.JButton();
        createResearchNameTextField = new javax.swing.JTextField();
        createResearchLbl2 = new javax.swing.JLabel();
        createResearchLbl3 = new javax.swing.JLabel();
        openPanel = new PresentationLayer.PanelRound();
        openAddBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        createResearchLbl1 = new javax.swing.JLabel();
        createResearchLbl = new javax.swing.JLabel();
        openResearchNameTextField = new javax.swing.JTextField();
        mergePanel = new PresentationLayer.PanelRound();
        mergeLbl = new javax.swing.JLabel();
        mergeBackBtn = new javax.swing.JButton();
        mergeActionBtn = new javax.swing.JButton();
        mergeResearch1ComboBox = new javax.swing.JComboBox<>();
        createResearchLbl9 = new javax.swing.JLabel();
        createResearchLbl10 = new javax.swing.JLabel();
        mergeResearch2ComboBox = new javax.swing.JComboBox<>();
        createResearchLbl11 = new javax.swing.JLabel();
        mergeResearchTextField = new javax.swing.JTextField();
        openResearchBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(7, 7, 57));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        researchTable.setAutoCreateRowSorter(true);
        researchTable.setBackground(new java.awt.Color(196, 182, 182));
        researchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Serial", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        researchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                researchTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(researchTable);
        if (researchTable.getColumnModel().getColumnCount() > 0) {
            researchTable.getColumnModel().getColumn(0).setMinWidth(70);
            researchTable.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 147, 377, 412));

        createResearchBtn.setBackground(new java.awt.Color(254, 194, 96));
        createResearchBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createResearchBtn.setForeground(new java.awt.Color(59, 24, 95));
        createResearchBtn.setText("Create  Research");
        createResearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createResearchBtnActionPerformed(evt);
            }
        });
        add(createResearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 71, -1, 33));

        updateResearchBtn.setBackground(new java.awt.Color(254, 194, 96));
        updateResearchBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        updateResearchBtn.setForeground(new java.awt.Color(59, 24, 95));
        updateResearchBtn.setText("Update Research");
        updateResearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateResearchBtnActionPerformed(evt);
            }
        });
        add(updateResearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 71, -1, 33));

        deleteResearchBtn.setBackground(new java.awt.Color(254, 194, 96));
        deleteResearchBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deleteResearchBtn.setForeground(new java.awt.Color(59, 24, 95));
        deleteResearchBtn.setText("Delete Research");
        deleteResearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteResearchBtnActionPerformed(evt);
            }
        });
        add(deleteResearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 71, -1, 33));

        mergeResearchBtn.setBackground(new java.awt.Color(254, 194, 96));
        mergeResearchBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        mergeResearchBtn.setForeground(new java.awt.Color(59, 24, 95));
        mergeResearchBtn.setText("Merge Research");
        mergeResearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mergeResearchBtnActionPerformed(evt);
            }
        });
        add(mergeResearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 71, -1, 33));

        actionPanel.setBackground(new java.awt.Color(7, 7, 57));
        actionPanel.setLayout(new java.awt.CardLayout());

        blankPanel.setBackground(new java.awt.Color(7, 7, 57));

        javax.swing.GroupLayout blankPanelLayout = new javax.swing.GroupLayout(blankPanel);
        blankPanel.setLayout(blankPanelLayout);
        blankPanelLayout.setHorizontalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        blankPanelLayout.setVerticalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        actionPanel.add(blankPanel, "blankPanel");

        deletePanel.setBackground(new java.awt.Color(47, 18, 76));
        openPanel.setAllCornersRound(40);

        deleteBtn.setBackground(new java.awt.Color(254, 194, 96));
        deleteBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(59, 24, 95));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        deleteBackBtn.setBackground(new java.awt.Color(254, 194, 96));
        deleteBackBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        deleteBackBtn.setForeground(new java.awt.Color(59, 24, 95));
        deleteBackBtn.setText("BACK");
        deleteBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBackBtnActionPerformed(evt);
            }
        });

        createResearchLbl7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createResearchLbl7.setForeground(new java.awt.Color(254, 194, 96));
        createResearchLbl7.setText("Select Research");

        createResearchLbl8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        createResearchLbl8.setForeground(new java.awt.Color(254, 194, 96));
        createResearchLbl8.setText("Delete Research");

        deleteResearchNameTextField.setEditable(false);
        deleteResearchNameTextField.setBackground(new java.awt.Color(196, 182, 182));
        deleteResearchNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteResearchNameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createResearchLbl7)
                            .addGroup(deletePanelLayout.createSequentialGroup()
                                .addComponent(deleteBackBtn)
                                .addGap(129, 129, 129)
                                .addComponent(deleteBtn))
                            .addComponent(deleteResearchNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(createResearchLbl8)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createResearchLbl8)
                .addGap(57, 57, 57)
                .addComponent(createResearchLbl7)
                .addGap(18, 18, 18)
                .addComponent(deleteResearchNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        actionPanel.add(deletePanel, "deletePanel");

        updatePanel.setBackground(new java.awt.Color(47, 18, 76));
        updatePanel.setAllCornersRound(40);

        updateBtn.setBackground(new java.awt.Color(254, 194, 96));
        updateBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(59, 24, 95));
        updateBtn.setText("ADD");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        updateBackBtn.setBackground(new java.awt.Color(254, 194, 96));
        updateBackBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        updateBackBtn.setForeground(new java.awt.Color(59, 24, 95));
        updateBackBtn.setText("BACK");
        updateBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBackBtnActionPerformed(evt);
            }
        });

        newNameTextField.setBackground(new java.awt.Color(196, 182, 182));
        newNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNameTextFieldActionPerformed(evt);
            }
        });

        createResearchLbl4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createResearchLbl4.setForeground(new java.awt.Color(254, 194, 96));
        createResearchLbl4.setText("Enter New Name");

        createResearchLbl5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        createResearchLbl5.setForeground(new java.awt.Color(254, 194, 96));
        createResearchLbl5.setText("Update Research");

        researchUpdateNameTextField.setEditable(false);
        researchUpdateNameTextField.setBackground(new java.awt.Color(196, 182, 182));
        researchUpdateNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                researchUpdateNameTextFieldActionPerformed(evt);
            }
        });

        createResearchLbl6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createResearchLbl6.setForeground(new java.awt.Color(254, 194, 96));
        createResearchLbl6.setText("Research Selected");

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(createResearchLbl5))
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(updatePanelLayout.createSequentialGroup()
                                .addComponent(updateBackBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateBtn))
                            .addComponent(newNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createResearchLbl6)
                            .addComponent(researchUpdateNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createResearchLbl4))))
                .addGap(87, 87, 87))
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(createResearchLbl5)
                .addGap(29, 29, 29)
                .addComponent(createResearchLbl6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(researchUpdateNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createResearchLbl4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        actionPanel.add(updatePanel, "updatePanel");

        createPanel.setBackground(new java.awt.Color(47, 18, 76));
        createPanel.setAllCornersRound(40);

        createAddBtn.setBackground(new java.awt.Color(254, 194, 96));
        createAddBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createAddBtn.setForeground(new java.awt.Color(59, 24, 95));
        createAddBtn.setText("ADD");
        createAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAddBtnActionPerformed(evt);
            }
        });

        createBackBtn.setBackground(new java.awt.Color(254, 194, 96));
        createBackBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createBackBtn.setForeground(new java.awt.Color(59, 24, 95));
        createBackBtn.setText("BACK");
        createBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBackBtnActionPerformed(evt);
            }
        });

        createResearchNameTextField.setBackground(new java.awt.Color(196, 182, 182));
        createResearchNameTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        createResearchNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createResearchNameTextFieldActionPerformed(evt);
            }
        });

        createResearchLbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createResearchLbl2.setForeground(new java.awt.Color(254, 194, 96));
        createResearchLbl2.setText("Enter Name");

        createResearchLbl3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        createResearchLbl3.setForeground(new java.awt.Color(254, 194, 96));
        createResearchLbl3.setText("Create New Research");

        javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
        createPanel.setLayout(createPanelLayout);
        createPanelLayout.setHorizontalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(createResearchLbl3))
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(createResearchLbl2))
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(createPanelLayout.createSequentialGroup()
                                .addComponent(createBackBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createAddBtn))
                            .addComponent(createResearchNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(87, 87, 87))
        );
        createPanelLayout.setVerticalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(createResearchLbl3)
                .addGap(58, 58, 58)
                .addComponent(createResearchLbl2)
                .addGap(15, 15, 15)
                .addComponent(createResearchNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        actionPanel.add(createPanel, "createPanel");

        openPanel.setBackground(new java.awt.Color(47, 18, 76));
        openPanel.setAllCornersRound(40);

        openAddBtn.setBackground(new java.awt.Color(254, 194, 96));
        openAddBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        openAddBtn.setForeground(new java.awt.Color(59, 24, 95));
        openAddBtn.setText("OPEN");
        openAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAddBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(254, 194, 96));
        backBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(59, 24, 95));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        createResearchLbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createResearchLbl1.setForeground(new java.awt.Color(254, 194, 96));
        createResearchLbl1.setText("Select Research");

        createResearchLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        createResearchLbl.setForeground(new java.awt.Color(254, 194, 96));
        createResearchLbl.setText("Open Research");

        openResearchNameTextField.setEditable(false);
        openResearchNameTextField.setBackground(new java.awt.Color(196, 182, 182));
        openResearchNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openResearchNameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout openPanelLayout = new javax.swing.GroupLayout(openPanel);
        openPanel.setLayout(openPanelLayout);
        openPanelLayout.setHorizontalGroup(
            openPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openPanelLayout.createSequentialGroup()
                .addGroup(openPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(openPanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(createResearchLbl))
                    .addGroup(openPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(openPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createResearchLbl1)
                            .addGroup(openPanelLayout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(129, 129, 129)
                                .addComponent(openAddBtn))
                            .addComponent(openResearchNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        openPanelLayout.setVerticalGroup(
            openPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createResearchLbl)
                .addGap(57, 57, 57)
                .addComponent(createResearchLbl1)
                .addGap(18, 18, 18)
                .addComponent(openResearchNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(openPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        actionPanel.add(openPanel, "openPanel");

        mergePanel.setBackground(new java.awt.Color(47, 18, 76));
        mergePanel.setAllCornersRound(40);

        mergeLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mergeLbl.setForeground(new java.awt.Color(254, 194, 96));
        mergeLbl.setText("Merge Research");

        mergeBackBtn.setBackground(new java.awt.Color(254, 194, 96));
        mergeBackBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        mergeBackBtn.setForeground(new java.awt.Color(59, 24, 95));
        mergeBackBtn.setText("BACK");
        mergeBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mergeBackBtnActionPerformed(evt);
            }
        });

        mergeActionBtn.setBackground(new java.awt.Color(254, 194, 96));
        mergeActionBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        mergeActionBtn.setForeground(new java.awt.Color(59, 24, 95));
        mergeActionBtn.setText("Merge");
        mergeActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mergeActionBtnActionPerformed(evt);
            }
        });

        createResearchLbl9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createResearchLbl9.setForeground(new java.awt.Color(254, 194, 96));
        createResearchLbl9.setText("Select 1st Research");

        createResearchLbl10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createResearchLbl10.setForeground(new java.awt.Color(254, 194, 96));
        createResearchLbl10.setText("Select 2nd Research");

        createResearchLbl11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createResearchLbl11.setForeground(new java.awt.Color(254, 194, 96));
        createResearchLbl11.setText("Enter New Research Name");

        mergeResearchTextField.setBackground(new java.awt.Color(196, 182, 182));
        mergeResearchTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mergeResearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mergeResearchTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mergePanelLayout = new javax.swing.GroupLayout(mergePanel);
        mergePanel.setLayout(mergePanelLayout);
        mergePanelLayout.setHorizontalGroup(
            mergePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mergePanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(mergeLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mergePanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(mergeBackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mergeActionBtn)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mergePanelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(mergePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createResearchLbl9)
                    .addComponent(createResearchLbl11)
                    .addComponent(mergeResearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mergeResearch2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createResearchLbl10)
                    .addComponent(mergeResearch1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        mergePanelLayout.setVerticalGroup(
            mergePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mergePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mergeLbl)
                .addGap(38, 38, 38)
                .addComponent(createResearchLbl9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mergeResearch1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createResearchLbl10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(mergeResearch2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createResearchLbl11)
                .addGap(15, 15, 15)
                .addComponent(mergeResearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mergePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mergeBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mergeActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        actionPanel.add(mergePanel, "card7");

        add(actionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 147, 420, 360));

        openResearchBtn.setBackground(new java.awt.Color(254, 194, 96));
        openResearchBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        openResearchBtn.setForeground(new java.awt.Color(59, 24, 95));
        openResearchBtn.setText("Open Research");
        openResearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openResearchBtnActionPerformed(evt);
            }
        });
        add(openResearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 71, -1, 33));
    }// </editor-fold>//GEN-END:initComponents

    private void createResearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createResearchBtnActionPerformed
        CardLayout cardLayout = (CardLayout) actionPanel.getLayout();
        cardLayout.show(actionPanel, "createPanel");

    }//GEN-LAST:event_createResearchBtnActionPerformed

    private void updateResearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateResearchBtnActionPerformed
        CardLayout cardLayout = (CardLayout) actionPanel.getLayout();
        cardLayout.show(actionPanel, "updatePanel");
    }//GEN-LAST:event_updateResearchBtnActionPerformed

    private void deleteResearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteResearchBtnActionPerformed
        CardLayout cardLayout = (CardLayout) actionPanel.getLayout();
        cardLayout.show(actionPanel, "deletePanel");
    }//GEN-LAST:event_deleteResearchBtnActionPerformed

    private void mergeResearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mergeResearchBtnActionPerformed
        CardLayout cardLayout = (CardLayout) actionPanel.getLayout();
        cardLayout.show(actionPanel, "card7");
    }//GEN-LAST:event_mergeResearchBtnActionPerformed

    private void openResearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openResearchBtnActionPerformed
        Research research = null;
        if (!openResearchNameTextField.getText().equals("")) {
            research = fascadeBLL.getResearch(openResearchNameTextField.getText());
        }
        if (research != null) {
            JPanel mainPanel = (JPanel) this.getParent();
            LandingPage landingPage = (LandingPage) mainPanel.getTopLevelAncestor();
            CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
            cardLayout.show(mainPanel, "card3");

            landingPage.researchPanel1.setReseach(research);
        }


    }//GEN-LAST:event_openResearchBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        CardLayout cardLayout = (CardLayout) actionPanel.getLayout();
        cardLayout.show(actionPanel, "blankPanel");
    }//GEN-LAST:event_backBtnActionPerformed

    private void openAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAddBtnActionPerformed
        if (!openResearchNameTextField.getText().equals("")) {
            JPanel mainPanel = (JPanel) this.getParent();
            LandingPage landingPage = (LandingPage) mainPanel.getParent().getParent();
            CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
            cardLayout.show(mainPanel, "mainPanel");
            Research research = fascadeBLL.getResearch(openResearchNameTextField.getText());
            landingPage.researchPanel1.setReseach(research);
        }

    }//GEN-LAST:event_openAddBtnActionPerformed

    private void createAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAddBtnActionPerformed
        if (fascadeBLL.createResearch(createResearchNameTextField.getText().toString())) {

            populateResearchTable(fascadeBLL.getAllResearches());
            JOptionPane.showMessageDialog(null, "Research Created ." + createResearchNameTextField.getText().toString(), "New Research", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(null, "Reseach with this name already exists.", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_createAddBtnActionPerformed

    private void createBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBackBtnActionPerformed
        CardLayout cardLayout = (CardLayout) actionPanel.getLayout();
        cardLayout.show(actionPanel, "blankPanel");
    }//GEN-LAST:event_createBackBtnActionPerformed

    private void createResearchNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createResearchNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createResearchNameTextFieldActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String newName = newNameTextField.getText();
        String oldName = researchUpdateNameTextField.getText();
        String newNameCleaned = newName.replaceAll(" ", "");
        if (!oldName.equals("") && !newNameCleaned.equals("")) {

            Research research = fascadeBLL.getResearch(oldName);
            if (fascadeBLL.updateResearchName(research.getResearchId(), newName)) {
                populateResearchTable(fascadeBLL.getAllResearches());
                JOptionPane.showMessageDialog(null, "Research name updated", "Successful", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Error in updating research name", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a research from table and enter new name ", "Warning", JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_updateBtnActionPerformed

    private void updateBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBackBtnActionPerformed
        CardLayout cardLayout = (CardLayout) actionPanel.getLayout();
        cardLayout.show(actionPanel, "blankPanel");
    }//GEN-LAST:event_updateBackBtnActionPerformed

    private void newNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newNameTextFieldActionPerformed

    private void researchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_researchTableMouseClicked
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        String researchName = researchTable.getValueAt(row, 1).toString();
        openResearchNameTextField.setText(researchName);
        researchUpdateNameTextField.setText(researchName);
        deleteResearchNameTextField.setText(researchName);
    }//GEN-LAST:event_researchTableMouseClicked

    private void openResearchNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openResearchNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openResearchNameTextFieldActionPerformed

    private void researchUpdateNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_researchUpdateNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_researchUpdateNameTextFieldActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String name = deleteResearchNameTextField.getText();
        if (!name.equals("")) {
            Research research = fascadeBLL.getResearch(name);
            if (research != null) {
                if (fascadeBLL.deleteResearch(research.getResearchId())) {
                    populateResearchTable(fascadeBLL.getAllResearches());
                    JOptionPane.showMessageDialog(null, "Research  deleted", "Successful", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Error in deleting research name", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please select a research from table", "Warning", JOptionPane.WARNING_MESSAGE);

            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void deleteBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBackBtnActionPerformed
        CardLayout cardLayout = (CardLayout) actionPanel.getLayout();
        cardLayout.show(actionPanel, "blankPanel");
    }//GEN-LAST:event_deleteBackBtnActionPerformed

    private void deleteResearchNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteResearchNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteResearchNameTextFieldActionPerformed

    private void mergeBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mergeBackBtnActionPerformed
        CardLayout cardLayout = (CardLayout) actionPanel.getLayout();
        cardLayout.show(actionPanel, "blankPanel");
    }//GEN-LAST:event_mergeBackBtnActionPerformed

    private void mergeActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mergeActionBtnActionPerformed
        if (!mergeResearch1ComboBox.getSelectedItem().toString().equals(mergeResearch2ComboBox.getSelectedItem().toString())) {
            Research research1 = fascadeBLL.getResearch(mergeResearch1ComboBox.getSelectedItem().toString());
            Research research2 = fascadeBLL.getResearch(mergeResearch2ComboBox.getSelectedItem().toString());
            String name = mergeResearchTextField.getText();
            boolean isMerged = fascadeBLL.mergeResearches(name, research1, research2);
            if (!isMerged) {
                JOptionPane.showMessageDialog(null, "Failed to merge researches. Check logs", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Merged Successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Both Researches cannot be same", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        populateResearchTable(fascadeBLL.getAllResearches());
    }//GEN-LAST:event_mergeActionBtnActionPerformed

    private void mergeResearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mergeResearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mergeResearchTextFieldActionPerformed

    private void populateResearchTable(ArrayList<Research> researches) {
        mergeResearch1ComboBox.removeAllItems();
        mergeResearch2ComboBox.removeAllItems();
        if (!researches.isEmpty()) {
            DefaultTableModel model = (DefaultTableModel) researchTable.getModel();
            model.setRowCount(0);
            int count = 1;
            for (Research research : researches) {
                Object[] row = {count, research.getName()};
                count++;
                model.addRow(row);
                mergeResearch1ComboBox.addItem(research.getName());
                mergeResearch2ComboBox.addItem(research.getName());
            }
            researchTable.setModel(model);
        } else {
            JOptionPane.showMessageDialog(null, "No Reseaches Found.", "Warning", JOptionPane.WARNING_MESSAGE);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel blankPanel;
    private javax.swing.JButton createAddBtn;
    private javax.swing.JButton createBackBtn;
    private PresentationLayer.PanelRound createPanel;
    private javax.swing.JButton createResearchBtn;
    private javax.swing.JLabel createResearchLbl;
    private javax.swing.JLabel createResearchLbl1;
    private javax.swing.JLabel createResearchLbl10;
    private javax.swing.JLabel createResearchLbl11;
    private javax.swing.JLabel createResearchLbl2;
    private javax.swing.JLabel createResearchLbl3;
    private javax.swing.JLabel createResearchLbl4;
    private javax.swing.JLabel createResearchLbl5;
    private javax.swing.JLabel createResearchLbl6;
    private javax.swing.JLabel createResearchLbl7;
    private javax.swing.JLabel createResearchLbl8;
    private javax.swing.JLabel createResearchLbl9;
    private javax.swing.JTextField createResearchNameTextField;
    private javax.swing.JButton deleteBackBtn;
    private javax.swing.JButton deleteBtn;
    private PresentationLayer.PanelRound deletePanel;
    private javax.swing.JButton deleteResearchBtn;
    private javax.swing.JTextField deleteResearchNameTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mergeActionBtn;
    private javax.swing.JButton mergeBackBtn;
    private javax.swing.JLabel mergeLbl;
    private PresentationLayer.PanelRound mergePanel;
    private javax.swing.JComboBox<String> mergeResearch1ComboBox;
    private javax.swing.JComboBox<String> mergeResearch2ComboBox;
    private javax.swing.JButton mergeResearchBtn;
    private javax.swing.JTextField mergeResearchTextField;
    private javax.swing.JTextField newNameTextField;
    private javax.swing.JButton openAddBtn;
    private PresentationLayer.PanelRound openPanel;
    private javax.swing.JButton openResearchBtn;
    private javax.swing.JTextField openResearchNameTextField;
    private javax.swing.JTable researchTable;
    private javax.swing.JTextField researchUpdateNameTextField;
    private javax.swing.JButton updateBackBtn;
    private javax.swing.JButton updateBtn;
    private PresentationLayer.PanelRound updatePanel;
    private javax.swing.JButton updateResearchBtn;
    // End of variables declaration//GEN-END:variables
}
